POST http://localhost:5000/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgyNDg4OCwiZXhwIjoxNjg4ODI0ODg4fQ.pn-jCTUB4NjZG3yh8eDA3RLdZRnC7UbarPnjM5hT6ZQ

{
    "name": "second company name"
}

### find one company by id 

GET http://localhost:5000/company/2 HTTP/1.1

### find all companies with name filter
GET http://localhost:5000/company?name=sec HTTP/1.1

### create office and attach company to it
POST http://localhost:5000/office HTTP/1.1
Content-Type: application/json

{
    "name" :"office name 3",
    "address": "office address name 3",
    "companyId": 2
}

### find one office with id
GET http://localhost:5000/office/1 HTTP/1.1

### sign up user
POST http://localhost:5000/user/create HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgxOTg0NSwiZXhwIjoxNjg4ODE5ODQ1fQ.oe2EeAM8rl2gFzYccfxAJcGYncTz1ZLYzxw2nGKxGeI

{
    "name" : "ahmed elmaghraby",
    "email":"amaghraby@test.com",
    "password": "12345678"
}

### create user type
POST http://localhost:5000/user/user-type HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NzgwMzgxNCwiZXhwIjoxNjg4ODAzODE0fQ.UtmgHCkDx1018lNOtCpwtr8Jl_oTPUV40PhmXGg9gXo

{
    "name": "employee"
}

### sign in
POST http://localhost:5000/user/signin HTTP/1.1
Content-Type: application/json

{
    "email":"super@super.com",
    "password":"123456"
}
### test
GET http://localhost:5000/user/test HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY4NzgwNTE5NywiZXhwIjoxNjg4ODA1MTk3fQ.ZmuWX1_vK743UHeR5ZzicTF10HnAhIQzdPNbStRFTXI

### create positions
POST http://localhost:5000/position HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgyNDg4OCwiZXhwIjoxNjg4ODI0ODg4fQ.pn-jCTUB4NjZG3yh8eDA3RLdZRnC7UbarPnjM5hT6ZQ

{
    "name":"manager"
}

### find position by company id
GET http://localhost:5000/position HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgyNDg4OCwiZXhwIjoxNjg4ODI0ODg4fQ.pn-jCTUB4NjZG3yh8eDA3RLdZRnC7UbarPnjM5hT6ZQ


### create department
POST http://localhost:5000/department HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgyNDg4OCwiZXhwIjoxNjg4ODI0ODg4fQ.pn-jCTUB4NjZG3yh8eDA3RLdZRnC7UbarPnjM5hT6ZQ

{
    "name": "random department name"
}

### find department by id
GET http://localhost:5000/department/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgyNDg4OCwiZXhwIjoxNjg4ODI0ODg4fQ.pn-jCTUB4NjZG3yh8eDA3RLdZRnC7UbarPnjM5hT6ZQ

### find departments by company id
GET http://localhost:5000/department?companyId=2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY4NzgyNDg4OCwiZXhwIjoxNjg4ODI0ODg4fQ.pn-jCTUB4NjZG3yh8eDA3RLdZRnC7UbarPnjM5hT6ZQ
